services:  
  dust216:
    build: .
    environment:
      PV_PORT: 7777
    ports:
      - "7777:7777"
      - "8177:8177"
      - "9100:9100"
    volumes:
      - ./dust216.ini:/home/steam/pavlovserver/Pavlov/Saved/Config/LinuxServer/Game.ini:ro
      - ./RconSettings_1.txt:/home/steam/pavlovserver/Pavlov/Saved/Config/RconSettings.txt:ro
    restart: unless-stopped
  
  dust2csgo:
    build: .
    environment:
      PV_PORT: 7778
    ports:
      - "7778:7778"
      - "8178:8178"
      - "9101:9101"
    volumes:
      - ./dust2csgo.ini:/home/steam/pavlovserver/Pavlov/Saved/Config/LinuxServer/Game.ini:ro
      - ./RconSettings_2.txt:/home/steam/pavlovserver/Pavlov/Saved/Config/RconSettings.txt:ro
    restart: unless-stopped
  