services:
  pavlovserver:
    build: .
    ports:
      - "7777:7777/udp"
      - "8177:8177/udp"
    volumes:
      - ./PavlovServerConfig_cs16.ini:/home/steam/pavlovserver/Pavlov/Saved/Config/LinuxServer/Game.ini
    restart: unless-stopped
